-- AlterTable
ALTER TABLE "Zone" ADD COLUMN     "layoutMode" TEXT NOT NULL DEFAULT 'auto';

-- AlterTable
ALTER TABLE "ZoneItem" ADD COLUMN     "h" DOUBLE PRECISION,
ADD COLUMN     "w" DOUBLE PRECISION,
ADD COLUMN     "x" DOUBLE PRECISION,
ADD COLUMN     "y" DOUBLE PRECISION;
